language: ruby

rvm:
  - 2.3.3
  - 2.4.1

before_install: "rm ${BUNDLE_GEMFILE}.lock"

before_script: "bundle update"

sudo: false

cache: bundler

gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails-4.2-stable

branches:
  only:
    master

services:
  - redis-server
